### ISSUE TITLE
回帖 ^ 字符会丢失

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#1008]
![wechatimg204](https://user-images.githubusercontent.com/5518/37077392-ca665436-2215-11e8-9b72-ede379405845.jpeg)

**Comment by huacnlee** [comment]
@hooopo 不是 Bug 这是 Markdown 的 `sup` 功能：

```
^Hello^
```

看来可以禁用掉，GitHub 也没有：

^Hello^

**Comment by hooopo** [comment]
记得之前没有这个特性
