### ISSUE TITLE
配置https功能失败 make install_ssl 命令失败

### ISSUE THREAD

**Issue by bobjiang** [ruby-china/homeland#1016]
在server上homeland根目录执行命令

`/var/opt/homeland-docker$ sudo make install_ssl`

ssl keys已经生成成功：

`[Tue Apr 10 22:45:38 UTC 2018] The domain key is here: /var/www/ssl/localhost/localhost.key  
[Tue Apr 10 22:45:38 UTC 2018] _createcsr  
[Tue Apr 10 22:45:38 UTC 2018] Single domain='localhost'  
[Tue Apr 10 22:45:38 UTC 2018] Getting domain auth token for each domain  
[Tue Apr 10 22:45:38 UTC 2018] Getting webroot for domain='localhost'  
[Tue Apr 10 22:45:38 UTC 2018] _w='/var/www/homeland/public'  
[Tue Apr 10 22:45:38 UTC 2018] _currentRoot='/var/www/homeland/public'  
[Tue Apr 10 22:45:38 UTC 2018] Getting new-authz for domain='localhost'  
[Tue Apr 10 22:45:38 UTC 2018] _init api for server: https://acme-v01.api.letsencrypt.org/directory  `

最后在authz的过程失败，错误如下：

[Tue Apr 10 22:45:39 UTC 2018] new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: DNS name does not have enough labels","status": 400}  

`[Tue Apr 10 22:45:38 UTC 2018] POST  
[Tue Apr 10 22:45:38 UTC 2018] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'  
[Tue Apr 10 22:45:38 UTC 2018] _CURL='curl -L --silent --dump-header /var/www/ssl/http.header '  
[Tue Apr 10 22:45:39 UTC 2018] _ret='0'  
[Tue Apr 10 22:45:39 UTC 2018] code='400'  
[Tue Apr 10 22:45:39 UTC 2018] The new-authz request is ok.  
[Tue Apr 10 22:45:39 UTC 2018] new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: DNS name does not have enough labels","status": 400}  
[Tue Apr 10 22:45:39 UTC 2018] pid    
[Tue Apr 10 22:45:39 UTC 2018] No need to restore nginx, skip.  
[Tue Apr 10 22:45:39 UTC 2018] _clearupdns  
[Tue Apr 10 22:45:39 UTC 2018] skip dns.  
[Tue Apr 10 22:45:39 UTC 2018] _on_issue_err  
[Tue Apr 10 22:45:39 UTC 2018] Please add '--debug' or '--log' to check more details.  
[Tue Apr 10 22:45:39 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh  
[Tue Apr 10 22:45:39 UTC 2018] Diagnosis versions:  
openssl:openssl  
OpenSSL 1.0.1f 6 Jan 2014  
apache:  
apache doesn't exists.  
nginx:  
nginx version: nginx/1.10.2  
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)  
built with OpenSSL 1.0.1f 6 Jan 2014`

**Comment by huacnlee** [comment]
localhost 当然不行啊，得真实的域名，并且确保绑定正确

**Comment by bobjiang** [comment]
hostname要配置正确的，对吧。

我先试试哈

**Comment by bobjiang** [comment]
我有真实域名，也在使用中，hiblock.net

有没有绑定域名的介绍或说明？

谢谢

**Comment by huacnlee** [comment]
https://gethomeland.com/docs/ssl/

**Comment by bobjiang** [comment]
解决了，还是app.local.env设置的不对。
我还在找哪里设置了localhost的，嘿嘿
