### ISSUE TITLE
markdown 上传图片不能正常显示

### ISSUE THREAD

**Issue by examplecode** [ruby-china/homeland#1046]
当前最新版本，在rails开发环境下部署。 markdown编辑器上传了图片无法正常显示。

生成的markdown 标记如下
```
![](/uploads/photo/2018/1ee48fdd-8056-4b88-83ff-29a3a536e5d2.png!large)

```

查看了upload目录发现文件 1ee48fdd-8056-4b88-83ff-29a3a536e5d2.png 已经存在

尝试去除了"!large" 后缀 发现可以正常显示了。

**Comment by huacnlee** [comment]
手动部署？

Nginx 缺少缩略图配置

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland-docker/blob/master/etc/nginx/homeland.conf#L79

**Comment by examplecode** [comment]
原来如此感谢回复，目前我是在rails 开发环境运行的，可否缩略图的配置只应用在生产环境？

**Comment by huacnlee** [comment]
https://gethomeland.com/docs/configuration/upload/

用云存储
在 2018年6月13日 +0800 11:13，chengkai <notifications@github.com>，写道：
