### ISSUE TITLE
bug第一次点关注或者取消关注点时候，关注者数量不会动

### ISSUE THREAD

**Issue by UOvOU** [ruby-china/homeland#1054]
如图，第一次点击关注，上面点关注者数是不会。第二次点击取消关注，关注者数量动了，却是加一！应该是减1才对。
![_f623e1a3-dc78-406c-8c2d-7deb64d3a4ec](https://user-images.githubusercontent.com/24560577/42300348-96350a8c-8042-11e8-96da-3ce495fa9e4a.png)

**Comment by huacnlee** [comment]
已经没这个问题了
