### ISSUE TITLE
能否在帖子详情页右下角再添加一个自定义html的区域

### ISSUE THREAD

**Issue by strahe** [ruby-china/homeland#1065]
![s](https://user-images.githubusercontent.com/7932644/44966690-2f9f4d80-af6f-11e8-9a3a-a0da36e9dd24.png)

这里下方有很大的空间, 感觉如果能自定义html的话, 会方便很多.
如果可以的话, 麻烦帮忙实现一下吧, 谢谢.

**Comment by huacnlee** [comment]
提 PR
