### ISSUE TITLE
用户改名失败，一直提示名称已占用

### ISSUE THREAD

**Issue by Laotree** [ruby-china/homeland#1071]
使用了各种奇怪的名字，但是都提示改不了
![image](https://user-images.githubusercontent.com/16837634/46062761-5f6ff880-c19d-11e8-88aa-64cde0693e39.png)

**Comment by huacnlee** [comment]
这个问已经解决了

**Comment by Laotree** [comment]
![image](https://user-images.githubusercontent.com/16837634/101283033-38002600-3813-11eb-8b94-f488216d8553.png)
好像还是存在？

**Comment by huacnlee** [comment]
Ruby China 的用户名发一下

**Comment by Laotree** [comment]
[Laotree](https://ruby-china.org/Laotree)
