### ISSUE TITLE
ssl配置失败，提示 '-w' is not a valid domain for parameter '-d'

### ISSUE THREAD

**Issue by injetlee** [ruby-china/homeland#1077]
root@VM-40-233-ubuntu:/home/ubuntu/homeland-docker# sudo make install_ssl
docker-compose start web
Starting web ... done
docker-compose run web ash -c 'echo $cert_domain'
Starting homeland_redis ... 
Starting homeland_postgresql ... 
Starting homeland_elasticsearch ... done
Starting homeland_worker ... 
Starting homeland_app ... 
Starting homeland_app_backup ... done

docker-compose run web ash -c '/root/.acme.sh/acme.sh --issue -d $cert_domain -w /home/app/homeland/public --home /home/app/ssl --debug'
Starting homeland_redis ... 
Starting homeland_postgresql ... 
Starting homeland_elasticsearch ... done
Starting homeland_worker ... 
Starting homeland_app ... 
Starting homeland_app_backup ... done
**[Sun Nov 11 13:35:35 UTC 2018] '-w' is not a valid domain for parameter '-d'**
Makefile:15: recipe for target 'install_ssl' failed
make: *** [install_ssl] Error 1
root@VM-40-233-ubuntu:/home/ubuntu/homeland-docker#

**Comment by injetlee** [comment]
我按照要求配置的，域名可以正常访问。

**Comment by zemora** [comment]
请问这个问题解决了吗？是怎么解决的？

**Comment by seabornlee** [comment]
遇到同样的问题。

**Comment by zwdgit** [comment]
+1

**Comment by huacnlee** [comment]
域名配置不对
