### ISSUE TITLE
移动设备视图文章目录索引显示不完整

### ISSUE THREAD

**Issue by examplecode** [ruby-china/homeland#1081]
当使用移动设备访问某一篇文章的时候，响应式设计切换至移动视图下。点击文章的目录索引，目录索引菜单显示不完整，只能显示一条目录内容。

**Comment by vincentying15** [comment]
问题出在[app/assets/stylesheets/toc.scss](https://github.com/ruby-china/homeland/blob/master/app/assets/stylesheets/toc.scss#L61-L62)中, line 61, 62
```css
height: 100%;
max-height: 100%;
```
限制了div box的高度，导致children目录无法正常显示。

解决方法很简单，改为
```css
height: auto;
max-height:none;
```

**Comment by vincentying15** [comment]
修改前：
<img width="385" alt="2018-12-26 12 57 12" src="https://user-images.githubusercontent.com/14367682/50424999-765fdd00-08a9-11e9-8e1c-970dbafb24ff.png">

修改后：
<img width="396" alt="2018-12-26 12 57 40" src="https://user-images.githubusercontent.com/14367682/50425001-8081db80-08a9-11e9-9958-26bc5773c101.png">

**Comment by vincentying15** [comment]
这个issue可以关闭了
