### ISSUE TITLE
Setting.index_html是不是没有定义了

### ISSUE THREAD

**Issue by balanceM** [ruby-china/homeland#1101]
在 `views/home/index.html.erb里面，
```
<% if !mobile? %>
<div class="hide-ios">
  <%= raw Setting.index_html %>
</div>
<% end %>
```
这里Setting.index_html是不是已经没有定义了？我好像没有找到定义的地方

**Comment by monsterooo** [comment]
如果没错，这个功能是由[rails-settings-cached](https://github.com/huacnlee/rails-settings-cached)来完成的
