### ISSUE TITLE
个人资料编辑出错

### ISSUE THREAD

**Issue by zyc945** [ruby-china/homeland#1110]
我用homeland搭建了一个论坛，一切都运行的很完美。只是填写个人资料后保存的时候会出错。
后台的错误信息如下：

> #<NoMethodError: undefined method `each' for nil:NilClass>
/home/app/homeland/app/models/user/profile_fields.rb:48:in `update_profile_fields'
/home/app/homeland/app/controllers/settings_controller.rb:86:in `update_profile'
/home/app/homeland/app/controllers/settings_controller.rb:28:in `update'
/home/app/homeland/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/app/homeland/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:194:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'

出错后会跳到“服务访问异常”页面，回到主页查看资料信息，实际上数据已经修改成功了。

**Comment by huacnlee** [comment]
用最新的 homeland/homeland:latest 部署一下，目前这个我查不到错误原因，代码行数不一样了
