### ISSUE TITLE
社区首页小提示显示问题

### ISSUE THREAD

**Issue by monsterooo** [ruby-china/homeland#1116]
@huacnlee  华顺哥，现在社区首页显示的小提示是这样的，是不是在编辑小提示的时候增加了换行符？

![image](https://user-images.githubusercontent.com/18432680/60577851-bc46b200-9db2-11e9-88f9-4486abc9abc5.png)

```ruby
def random_tips
  tips = Setting.tips
  return "" if tips.blank?
  tips.split("\n").sample
end
```

**Comment by huacnlee** [comment]
上次重构漏掉了

**Comment by monsterooo** [comment]
嗯 好的
