### ISSUE TITLE
ruby-china 旧文章无法搜索到

### ISSUE THREAD

**Issue by yfractal** [ruby-china/homeland#1129]
比如 [自旋锁 (spinlock) 及 nginx 的实现](https://ruby-china.org/topics/37916) 这篇文章，
我搜索 spinlock 就搜索不到

<img width="1020" alt="Screen Shot 2019-07-25 at 11 10 17 PM" src="https://user-images.githubusercontent.com/3775525/61885975-65f00d80-af31-11e9-9a8b-b739f8695917.png">
https://ruby-china.org/search?q=spinlock

但最近的似乎可以搜索到：

<img width="1010" alt="Screen Shot 2019-07-25 at 11 11 05 PM" src="https://user-images.githubusercontent.com/3775525/61886022-8029eb80-af31-11e9-95a9-8718b3efbeea.png">

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/pull/1165
