### ISSUE TITLE
准备给几十万PC用户搭建一个homeland在线的论坛，我们的一点需求

### ISSUE THREAD

**Issue by ygihjsg1** [ruby-china/homeland#1141]
我们做新媒体产品，每天有几十万的用户在PC端的产品里活跃，决定基于homeland开发社区。

目前我们有这样的一些需求，我们有精力会自己开发，不过先反馈给Homeland的各位开发大大：

1. 回帖排序需求：目前仅支持按时间倒序，希望新增“时间顺序”、“点赞倒序”、“综合排序”（基于时间和点赞的综合排序）

2. 编辑器：目前的编辑器仅支持markdown格式，无法所见即所得地编辑，可能对我们的用户来讲会不太习惯，希望有简单的图文版本的编辑器（标题、加粗、图片、超链接）

3. 个人订阅的feed：目前关注用户、关注话题、关注节点的动态都是以通知的方式提醒，希望在首页增加个人订阅的feed流

**Comment by lypinggan** [comment]
编辑器支持附件上传也是蛮重要的。
