### ISSUE TITLE
WiKi插件的修正记录和次数不生效

### ISSUE THREAD

**Issue by wuyahui** [ruby-china/homeland#1153]
![image](https://user-images.githubusercontent.com/10398980/76192435-c4e26880-621c-11ea-88c6-b1dca600ec6e.png)

修改了N次了，但是这个次数还是为0，请问是什么问题？

**Comment by huacnlee** [comment]
https://github.com/homeland-plugins/wiki/commit/9103409addd5d2bdb8b66ba6a67a8a655b983915

已经修复，重新下载包安装

**Comment by wuyahui** [comment]
谢谢
