### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by denven** [ruby-china/homeland#1161]
make install shows error of elasticsearch installation:

**Errno::ECONNREFUSED: Connection refused - connect(2) for "elasticsearch" port 9200**
or
**Faraday::ConnectionFailed: Failed to open TCP connection to elasticsearch:9200**

The installation quit with this error.

When I run the web application, the search feature doesn't work, it says:
**对不起，由于某些原因导致功能异常，请稍后再试.
返回首页**

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/pull/1165
