### ISSUE TITLE
app_name无法使用中文

### ISSUE THREAD

**Issue by zwying0814** [ruby-china/homeland#1175]
虽然可以正常安装，运行，但是会出现：
服务访问异常 :( 对不起,由于某些原因导致功能异常,请稍后再试.

解决办法就是把app.local.env里的app_name换成非中文的

**Comment by huacnlee** [comment]
你的 Docker 主机不是中文的吧，你把中文包装上就可以了

**Comment by huacnlee** [comment]
已修改，最新版本可以直接在后台修改 app_name，不需要用环境变量配置
