### ISSUE TITLE
记事本编辑按钮 <i class="fa fa-pencil"></i> 显示不了

### ISSUE THREAD

**Issue by huobazi** [ruby-china/homeland#1176]
![{87E513CB-C84A-461A-8FD1-2E6661DDD565}_20200810174039](https://user-images.githubusercontent.com/341526/89770422-568a3500-db31-11ea-958d-2ac1613ad50f.jpg)
![{024010BE-8449-4B3A-9953-2FF569EF7502}_20200810174101](https://user-images.githubusercontent.com/341526/89770431-5ab65280-db31-11ea-9a94-e772260e4598.jpg)
![{AE08CBCE-AAB9-40E1-B91F-D59D421207AD}_20200810174216](https://user-images.githubusercontent.com/341526/89770446-5db14300-db31-11ea-92c0-ab3206f03bf1.jpg)

**Comment by icecoll** [comment]
那个要`Font Awesome Pro`才行
