### ISSUE TITLE
开启 SSL/HTTPS 功能失败

### ISSUE THREAD

**Issue by liuziwen483** [ruby-china/homeland#1188]
![image](https://user-images.githubusercontent.com/54828688/92695552-31c8ed80-f37b-11ea-9034-dcdc10ea18d9.png)
root@EOSnode08:/home/homeland-docker# sudo make install_ssl
sudo: unable to resolve host EOSnode08
docker-compose start web
Starting web ... done
docker-compose run web bash -c 'echo $cert_domain'
Starting homeland_redis ... done
Starting homeland_postgresql ... done
Starting homeland_worker     ... done
Starting homeland_app_backup ... done
Starting homeland_app        ... done
docker-compose run web bash -c '/root/.acme.sh/acme.sh --issue -d $cert_domain -w /home/app/homeland/public --home /home/app/ssl --debug'
Starting homeland_postgresql ... done
Starting homeland_redis      ... done
Starting homeland_worker     ... done
Starting homeland_app_backup ... done
Starting homeland_app        ... done
[Thu Sep 10 07:26:43 UTC 2020] '-w' is not a valid domain for parameter '-d'
Makefile:14: recipe for target 'install_ssl' failed
make: *** [install_ssl] Error 1
root@EOSnode08:/home/homeland-docker#

**Comment by huacnlee** [comment]
`cert_domain` 配置没有配置，这个是用来申请 SSL 证书的配置

**Comment by huacnlee** [comment]
https://homeland.ruby-china.org/docs/ssl/
