### ISSUE TITLE
如何让dark mode非强制跟随系统

### ISSUE THREAD

**Issue by deephanwang** [ruby-china/homeland#1189]
新版会使用@media (prefers-color-scheme: dark)跟随系统
请问有没有什么方法把默认跟随系统关掉
或者可选
我个人还是挺喜欢light颜色的

谢谢

**Comment by Dounx** [comment]
我觉得可以在在这里添加一个按钮来控制？

![image](https://user-images.githubusercontent.com/16432276/93991676-220bc900-fdbf-11ea-8b5c-6258a2d89c94.png)

**Comment by Dounx** [comment]
@huacnlee 我国庆可以试着写下？

如果没有设置过就跟随系统，设置存到 localStorge，然后利用 CSS 的属性选择器来切换暗黑模式。

**Comment by deephanwang** [comment]
@Dounx 这个可能有一些思路帮助
https://github.com/GoogleChromeLabs/dark-mode-toggle

**Comment by huacnlee** [comment]
macOS 系统设置可以开关，我感觉不需要做这个功能

**Comment by Dounx** [comment]
> macOS 系统设置可以开关，我感觉不需要做这个功能

我记得之前在论坛里看到有 svg 格式的流程图，黑色背景下就看不见，只能切换到白色背景下看，但是看完之后又想切回暗黑模式，就有了这种需求...

![black](https://user-images.githubusercontent.com/16432276/94533188-6e4c8280-0271-11eb-8499-de68d4741078.png)

![white](https://user-images.githubusercontent.com/16432276/94533197-70aedc80-0271-11eb-9ab9-0a48e675ebd9.png)
