### ISSUE TITLE
在手机竖屏时的topic列表中显示topic的更新时间信息

### ISSUE THREAD

**Issue by xiaoboa** [ruby-china/homeland#1211]
当手机竖屏时( 页面宽度小于480时），topic列表中的更新时间信息不会显示。

大部分手机上的竖屏页面宽度都是小于480的，而topic的更新时间是一项重要的信息，应该和title，author一样的重要，都应该被zhan展示出来

![image](https://user-images.githubusercontent.com/1646785/97524008-9baa5e80-19de-11eb-98a5-c55ea686b054.png)
![image](https://user-images.githubusercontent.com/1646785/97524085-c3012b80-19de-11eb-8dfd-e2a45ced2972.png)

**Comment by huacnlee** [comment]
不是 Bug，特意隐藏

**Comment by xiaoboa** [comment]
能知道为啥特意隐藏吗？

因为大部分手机上使用，基本上都是小于480的窗口，没有更新时间这个信息真的不方便
