### ISSUE TITLE
打算提交一个 pull request，增加渲染 mathjax 数学公式的功能，请问能接受吗

### ISSUE THREAD

**Issue by neozhaoliang** [ruby-china/homeland#1213]
如题，我想在搭建的论坛里面可以使用数学公式，打算提个 pr 加入这个功能，希望能合并到官方版本里面，请问是否接受加入这样的特性？

**Comment by huacnlee** [comment]
不接受，除非有非常权威的三方网站支持，类似 Codepen 之类的

**Comment by neozhaoliang** [comment]
这个特性本身就是权威网站支持的，见 www.mathjax.org，属于网页渲染数学公式的业内标准。
