### ISSUE TITLE
关于邮件发送的问题

### ISSUE THREAD

**Issue by itviewer** [ruby-china/homeland#1221]
版本，Homeland 3.8.0.beta2
目前**调通**了遇到的两个问题：
1、必须使用 ssl 发送的 smtp 服务器支持
目前很多邮件服务器如 qq 和 腾讯企业邮箱已经不支持 25 端口，要求必须使用支持 ssl 的端口 465
文件 https://github.com/ruby-china/homeland/blob/master/app/models/setting.rb 中 对 mailer_options 的处理缺少 ssl 选项
导致无法建立连接
添加
`ssl: (ENV["mailer_options_ssl"] || ENV["mailer_options.ssl"]),`
后解决
需要说明的是，类似 `mailer_options.ssl` 配置方式 ENV 根本获取不到内容，必须使用 `mailer_options_ssl` 方式，其它mailer_options一样
这个解决了重置密码时的发送邮件问题，配置格式
```
mailer_provider=smtp
mailer_sender="EasySoC <itviewer@easysoc.cn>"
mailer_options_address=smtp.exmail.qq.com
mailer_options_port=465
mailer_options_domain=easysoc.cn
mailer_options_user_name=itviewer@easysoc.cn
mailer_options_password=password
mailer_options_authentication=plain
mailer_options_enable_starttls_auto=false
mailer_options_ssl=true
```
2、注册发送邮件问题
在文件 https://github.com/ruby-china/homeland/blob/master/app/models/user.rb 中，
`UserMailer.welcome(id).deliver_later` 这一行前几天还没有注释掉，由于异步发送，导致总是报 timeout 异常，
结合 1，然后改为同步发送 `UserMailer.welcome(id).deliver_now`，可正常发送注册邮件。
至于为什么异步的 deliver_later 无法正常发送，猜测估计是无法正常获取 smtp_settings，不过不知道原因

**Comment by huacnlee** [comment]
enable_starttls_auto 设置为 false 即可

**Comment by itviewer** [comment]
@huacnlee 
官方文档 https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration ，smtp_settings 的最后一项或许才是对 ssl 是否启用的配置
```
:ssl/:tls - Enables the SMTP connection to use SMTP/TLS (SMTPS: SMTP over direct TLS connection)
```
也许不同的 smtp 服务器有不同的设置，我去掉 ssl 的配置又测试了下，至少对腾讯的邮箱，不加 `mailer_options_ssl=true` 是连不上的，感觉 `enable_starttls_auto` 这项配置和 ssl 没有关系，建议在文件
https://github.com/ruby-china/homeland/blob/master/app/models/setting.rb
中加入对 ssl 的配置
`ssl: (ENV["mailer_options_ssl"] || ENV["mailer_options.ssl"]),`

**Comment by itviewer** [comment]
@huacnlee 
死磕腾讯系邮箱又总结出了新的配置
参考了
https://zhidao.baidu.com/question/221666455.html
https://baike.baidu.com/item/STARTTLS

关于普通的 qq 邮箱，其有说明可以使用 465或587端口
https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=167
关于腾讯企业邮箱，其官方说明只有465端口，其实也可以用587端口
https://service.exmail.qq.com/cgi-bin/help?subtype=1&id=28&no=1000585

如果使用最开始说的，增加 `mailer_options_ssl=true`，其适合腾讯企业邮箱465端口，不能使用587端口
对于普通 qq 邮箱，无论什么情况，使用 465 端口都无法发送邮件，必须使用587端口

就目前的代码来看，只要设置端口为587，无论是腾讯企业邮箱还是普通qq邮箱都可以正常发邮件了
