### ISSUE TITLE
make update执行更新失败

### ISSUE THREAD

**Issue by zwdgit** [ruby-china/homeland#1228]
Error response from daemon: No such image: homeland/homeland:latest
Makefile:22: recipe for target 'update' failed
make: *** [update] Error 1

**Comment by huacnlee** [comment]
<img width="1562" alt="截屏2020-11-25 11 36 12" src="https://user-images.githubusercontent.com/5518/100180121-7bed5400-2f12-11eb-8296-3eeb8aff33e4.png">

https://hub.docker.com/r/homeland/homeland/tags?page=1&ordering=last_updated

感觉可能是你的网络问题

**Comment by zwdgit** [comment]
现在配置的是阿里云的镜像源，是因为没有同步过来的原因吗
