### ISSUE TITLE
镜像打包特别慢，在Coding上构建会超时

### ISSUE THREAD

**Issue by seabornlee** [ruby-china/homeland#1236]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/735708/102005885-6d4acd80-3d57-11eb-8ee1-4848eb6fe73b.png">

**Comment by seabornlee** [comment]
提交了 PR https://github.com/ruby-china/homeland/pull/1237

**Comment by oslivan** [comment]
@seabornlee 你这样改了之后，用 travis 跑的时候就会变慢的

**Comment by huacnlee** [comment]
见 https://github.com/ruby-china/homeland/pull/1237
