### ISSUE TITLE
发现数据库密码过于简单，必须要fork代码才能改数据库密码吗

### ISSUE THREAD

**Issue by zwdgit** [ruby-china/homeland#1239]

**Comment by dsh0416** [comment]
根据 `.env` 文件自行创建 `.env.local` 文件，在新建的文件中修改密码。Docker 部署时挂载新添加的文件到镜像中即可。

或者 clone 项目后自行添加 `.env.local` 重新 build Docker 镜像也可。

**不要将生产环境的密码放在任何可以被 git track 的代码中，这是非常危险的安全实践。**

**Comment by zwdgit** [comment]
> 根据 `.env` 文件自行创建 `.env.local` 文件，在新建的文件中修改密码。Docker 部署时挂载新添加的文件到镜像中即可。
> 
> 或者 clone 项目后自行添加 `.env.local` 重新 build Docker 镜像也可。
> 
> **不要将生产环境的密码放在任何可以被 git track 的代码中，这是非常危险的安全实践。**

请问可以请教一下在.env.local中是怎么配置的吗，应该修改哪个配置项

**Comment by dsh0416** [comment]
`.env` 文件相当于配置的模板，里面都是你可以根据实际情况修改的模板。增加 `DATABASE_URL=...` 这一行就是你需要连接的数据库的配置。
