### ISSUE TITLE
注册账号，验证码错误

### ISSUE THREAD

**Issue by sanjinhub** [ruby-china/homeland#1242]
![image](https://user-images.githubusercontent.com/53846155/103007282-166ea080-456e-11eb-8277-58d0bad9ab4e.png)

检测过网络，是没问题的。重装了很多次也不行

**Comment by huacnlee** [comment]
不是 Docker 安装的？

**Comment by sanjinhub** [comment]
@huacnlee 是 Docker 安装的，第一次安装没有问题，后来换了台服务器就这样了。香港服务器，网络没问题。

**Comment by Dounx** [comment]
话说这个问题之前 Ruby China 有段时间也这样，然后过了一会它自己好了。

**Comment by sanjinhub** [comment]
@Dounx 我也查了很多资料，你说的这些我都看到了。目前为止还是不知道为什么。
@huacnlee 等作者帮助解决

**Comment by huacnlee** [comment]
我刚试了一下，基于 homeland-docker 新部署了一个，验证码没有问题。

你给的信息太少了，有网站地址码？homeland-docker 有没有单独修改过？

**Comment by sanjinhub** [comment]
@huacnlee 刚刚重新部署了个，还是这个问题。演示地址：https://x.w5.io

**端口配置：**

> 只修改了 两处端口，5432 映射出来，方便本地连接管理。服务器 80 端口被占用，改成了 9090

 - "0.0.0.0:5432:5432"
 - "9090:80"

通过服务器 Nginx 反向代理 9090 进行访问。

**配置文件：**

- domain=localhost
- admin_emails=lauixData@gmail.com

**Comment by huacnlee** [comment]
域名配置必须和实际使用的用的一致

SanJin <notifications@github.com>于2020年12月27日 周日下午8:31写道：

**Comment by sanjinhub** [comment]
@huacnlee 
配置文件已经改成：domain=x.w5.io ，并且进行了重启。还是提示验证码不正确

**Comment by sanjinhub** [comment]
感谢，找到问题了，https 反代就不可以，http 就没问题

**Comment by sanjinhub** [comment]
还是验证码的问题，目前使用了最新版本的 Docker，使用内置的  Caddy Server 。开启了 SSL，注册的时候提示验证码不正确。

```
# App Config
domain=w5soar.com
https=true
admin_emails=lauixData@gmail.com
```

地址：https://w5soar.com

![image](https://user-images.githubusercontent.com/53846155/103615002-c11a9200-4f64-11eb-931d-4f60e967d238.png)

http 应该是可以的，但是我更需要使用 HTTPS。

**Comment by huacnlee** [comment]
@sanjinhub 你前端是不是有额外的 Nginx 代理？

**Comment by sanjinhub** [comment]
@huacnlee 已经去掉了，直接使用内置的 Caddy 。如果你不知道什么问题，可以留个邮箱，我把服务器账号密码发给你看看。

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/commit/df624978abf0decbb12055d938efcb83028f51ad

我默认禁用掉了验证码，你更新 3-8-latest 试试

**Comment by sanjinhub** [comment]
![image](https://user-images.githubusercontent.com/53846155/103637310-4498ab00-4f86-11eb-98f8-f775dab4c319.png)

注册账号后，跳到 https://web:80。

话说 homeland 有赞助地址吗？我在官网上没找到。

**Comment by huacnlee** [comment]
看起来你是额外配置了东西的，你可以，传递信息的时候丢失了。

你是怎么部署的，说清楚一些。另外你最好只用 homeland-docker 来部署，不要自己额外搞东西，那样我很难一一兼容解决。

**Comment by sanjinhub** [comment]
@huacnlee 并没有额外搞东西，完全基于 homeland-docker 来部署的。按照文档一步一步来的，使用最新的版本，注册后直接跳转到 https://web:80

**Comment by huacnlee** [comment]
你再更新一下 homeland-docker，确实是因为 Caddy Server 的配置有问题，导致 Host 不对，验证码也是这个问题。

**Comment by sanjinhub** [comment]
@huacnlee 十分感谢，我这边可以使用了，https://w5soar.com ，请问有赞助地址吗？如果没有加个微信吧，直接转账

**Comment by huacnlee** [comment]
https://ruby-china.org/huacnlee

页面左侧有个按钮

SanJin <notifications@github.com>于2021年1月6日 周三下午10:11写道：
