### ISSUE TITLE
缺少节点入口

### ISSUE THREAD

**Issue by Dounx** [ruby-china/homeland#1255]
现在页面上没有全部节点列表以及某个节点下所有话题的入口。

比如：https://ruby-china.org/topics/node1

**Comment by Dounx** [comment]
NodesController#index 方法现在是不是已经没有地方用到了。

**Comment by huacnlee** [comment]
需求量少，我在最近的版本里面弱化了节点功能：

- 去掉一级节点（Section），改为一层
- 去掉索引功能，似乎没多大必要（后续有新方案我会考虑看看）
