### ISSUE TITLE
ssl始终没有配置成功

### ISSUE THREAD

**Issue by zwdgit** [ruby-china/homeland#1265]
在app.local.env里面已经配置了domain
访问 http://domain:18080是可以的，但是访问 
https://domain:10443
https://domain:18080
https://domain:10080
都不可以，不知道问题出在哪

![image](https://user-images.githubusercontent.com/28926324/109445205-0dbcae00-7a7a-11eb-88a8-edd25a9f93ef.png)

**Comment by zwdgit** [comment]
看日志会请求 http://domain/.well-known/xxx，但是进到容器里面确实没有这个文件夹

![image](https://user-images.githubusercontent.com/28926324/109462107-f68fb780-7a9d-11eb-9c38-42fc09826911.png)

**Comment by zwdgit** [comment]
前端没有挂nginx，是用docker部署的

**Comment by zwdgit** [comment]
![image](https://user-images.githubusercontent.com/28926324/109464876-54be9980-7aa2-11eb-8f98-8ef7d6d5cec5.png)

**Comment by zwdgit** [comment]
试了以下，如果用nginx代理并配置证书的话，会导致无法正常登录或退出

**Comment by huacnlee** [comment]
1. 确保域名外网可以访问；
2. 用 `docker-compose logs -f caddy` 看看日志；
