### ISSUE TITLE
已删除用户影响 GitHub 登录绑定

### ISSUE THREAD

**Issue by chunlea** [ruby-china/homeland#1290]
我的 GitHub 账号登录 Ruby China 每次都会登录 https://ruby-china.org/chunlea-github 这个账号，但是这个账号跟我已经在用的账号（https://ruby-china.org/chunlea）是两个独立账号。并且我目前在用的账号的登录邮箱跟 GitHub 的主邮箱是一致的。所以导致我无法绑定 GitHub 登录到我已经使用的账号上。

从代码上看，现在用户是软删的，https://github.com/ruby-china/homeland/blob/87c52394f6248e3242e1acca1b2138d096264289/lib/homeland/sso.rb#L81-L112 这个地方也是有根据邮箱地址进行 match 用户的操作。但是删除用户的时候，没有删除对应的 `UserSSO` 导致每次登录都会登录到之前绑定的但是已经删除的用户。

https://github.com/ruby-china/homeland/blob/87c52394f6248e3242e1acca1b2138d096264289/app/controllers/settings_controller.rb#L36-L48

**Comment by huacnlee** [comment]
我先把账号恢复了，你现在可以绑定了

**Comment by chunlea** [comment]
感谢，我尝试绑定了一下，但是发现还是绑定到了 https://ruby-china.org/chunlea-github 这个账号。个人设置中的 email 跟之前的比多了一个 `1`, 感觉还是有问题。

**Comment by chunlea** [comment]
绑定成功了，我发现登陆之后可以看到解绑 GitHub 登陆，但是按钮的 icon 可能迷惑了我。解绑之后重新登陆可以绑定。感谢。
