### ISSUE TITLE
homeland部署之后无法通过ip访问

### ISSUE THREAD

**Issue by sai1024** [ruby-china/homeland#1306]
你好，我通过`https://homeland.ruby-china.org/zh-CN/`在服务器上docker部署之后。
-> 输入`docker ps`
![image](https://user-images.githubusercontent.com/56356960/146733829-2493044d-64ed-4d10-af04-19272526a386.png)

-> `docker logs`
![image](https://user-images.githubusercontent.com/56356960/146733925-45749a12-0e12-4158-b920-c53b2ed7cc24.png)

无法通过公网ip来访问

还有个很奇怪的就是：
不知道是谁在扫描我的服务器，都是200的
![20211220160346](https://user-images.githubusercontent.com/56356960/146733985-d19d836e-5cde-42df-8438-40a9e592be85.jpg)

谢谢～

**Comment by sai1024** [comment]
`app.local.env`:

```
"app.local.env" 14L, 282C                                                                                                                                                             11,1          All
RAILS_ENV=production
# RAILS_LOG_TO_STDOUT=true

# Database
DATABASE_URL=postgres://postgres:@postgresql:5432/homeland
# DATABASE_POOL=64
REDIS_URL=redis://redis:6379/1

# App Config
#app_name=我不爱学习
#domain=127.0.0.1
#cert_domain=127.0.0.1

# admin_emails=admin@admin.com
```

**Comment by sai1024** [comment]
@huacnlee 大佬，请指教😭

**Comment by huacnlee** [comment]
配置一个域名访问
