### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by ichelash** [ruby-china/homeland#1308]
It's me again..I have installed homeland via docker..but I have tried to change the locale to en" restart the app, but I can't quite figure how to make the app run in English on everything. That's backend and fronted. Any help will be appreciated

**Comment by qichunren** [comment]
There are some text not translated. I will fix this.

**Comment by ichelash** [comment]
> There are some text not translated. I will fix this.

Okay..that will be great. Thanks for the feedback.
