### ISSUE TITLE
切换前端构建方案到 Rails 7

### ISSUE THREAD

**Issue by qichunren** [ruby-china/homeland#1326]
* Drop webpacker 6.0.0.rc.6
* Use CSS/JS bundling
* js的构建具体使用哪一个工具(webpack / esbuild)，先研究一下

**Comment by huacnlee** [comment]
我建议继续 Webpacker，前端部分往前端社区靠拢。Rails 这几年前端框架的方案变几次了。新的框架持续性有待观察，况且我期望走 React 的方式会更依赖 Webpack 那套工具链。

**Comment by qichunren** [comment]
Webpacker 升级到了 shakapacker 6.2.0
