### ISSUE TITLE
Use Tailwind CSS

### ISSUE THREAD

**Issue by qichunren** [ruby-china/homeland#1327]
打算移除 bootstrap, 采用 Tailwindcss.

 具体不知道工作量有多少，可以先应用在后台管理，再接着一步一步应用到前台。

**Comment by huacnlee** [comment]
其实我一直想用 React + TailwindCSS 重写前端

**Comment by laeo** [comment]
我发现 gocn 的主题很好看，就是不知道是不是已经没用 homeland 了

**Comment by csc449** [comment]
> 

一段时间以前华顺好像不prefer在web应用里用react, https://ruby-china.org/topics/39801, 最近看法有改变吗？

**Comment by BeanWei** [comment]
> 我发现 gocn 的主题很好看，就是不知道是不是已经没用 homeland 了

前端是用的 ant-design,  后端估计用的是go

**Comment by qichunren** [comment]
现在已经应用上了 TailwindCSS, 目前和 Bootstrap CSS 是共存状态，可以一起工作。后续将完全采用 TailwindCSS
