### ISSUE TITLE
postmark邮箱遇到 OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by pirunxi** [ruby-china/homeland#1353]
我们按照文档是这样配置的

mailer_provider=postmark
mailer_sender=no-reply@xxxx
mailer_options_api_key=e3bce1fe-18a4-4d65-90e6-590717xxxxxx

但运行起来报错，网上的回答是 SSL版本太低导致，这个如何解决呢

#<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello>

/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
/usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/local/lib/ruby/2.7.0/net/http.rb:1506:in `send_entity'
/usr/local/lib/ruby/2.7.0/net/http.rb:1294:in `post'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/http_client.rb:33:in `block in post'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/http_client.rb:93:in `block in do_request'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/http_client.rb:92:in `synchronize'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/http_client.rb:92:in `do_request'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/http_client.rb:33:in `post'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/api_client.rb:38:in `block (2 levels) in deliver_message'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/client.rb:58:in `take_response_of'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/api_client.rb:38:in `block in deliver_message'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/client.rb:39:in `with_retries'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/api_client.rb:37:in `deliver_message'
/usr/local/bundle/gems/postmark-1.21.2/lib/postmark/handlers/mail.rb:14:in `deliver!'
/usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/base.rb:559:in `block in deliver_mail'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/base.rb:557:in `deliver_mail'
/usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/usr/local/bundle/gems/actionmailer-6.1.0/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:28:in `instrument'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/logging.rb:22:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/logging.rb:22:in `tag_logger'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/execution.rb:47:in `perform_now'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/execution.rb:25:in `block in execute'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:84:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/execution.rb:23:in `execute'
/usr/local/bundle/gems/activejob-6.1.0/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:196:in `execute_job'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:163:in `block in process'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:111:in `local'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:14:in `block in call'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:257:in `stats'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:78:in `global'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:33:in `prepare'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/s

**Comment by Eric-Guo** [comment]
换一个新一点的操作系统，比如Rocky Linux 8.3?

**Comment by pirunxi** [comment]
> 换一个新一点的操作系统，比如Rocky Linux 8.3?

用的是阿里云的  自主研发的 ali xxx linux版本。。。难道要我们改这个。。。。。

**Comment by huacnlee** [comment]
用 Docker 部署，不然这类问题你得自己解决
