### ISSUE TITLE
论坛深色模式有问题

### ISSUE THREAD

**Issue by Dounx** [ruby-china/homeland#1379]
<img width="1440" alt="截屏2023-05-19 14 34 38" src="https://github.com/ruby-china/homeland/assets/16432276/f6b7d337-ccfa-4f8a-991a-7599613a448b">

帖子的标题以及挺多地方的颜色不对。

复现步骤：
1. https://ruby-china.org/setting
2. 主题偏好设置为深色模式

**Comment by qichunren** [comment]
已修复
