### ISSUE TITLE
禁止新注册的用户发帖

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#160]
#### 原因

越来越发现很多新用户以来就提一些没有经过思考的问题
- 本来之前有提过的，但他们不会尝试着搜索；
- 遇到一点小问题就开始发帖求帮助（但实际上等别人回答的时候，他自己却解决了）
- Wiki 或 Ruby 官方,Rails 官方的文档里面有的内容并且很明显的内容，但没有看过；
- 随便 Google 就能找到的内容；

还有就是新来的人普遍不会发帖，发出来的东西乱七八糟，甚至描述不清楚
#### 限制方案
- 新注册用户不到 1 个月内不能发帖，并且有过 10 次以上的回复
- 必须有头像

**Comment by Wumingla** [comment]
您好，管理员，打扰下，现在这个规定还在吗?我之前为了测试ruby-china的数据库某个地方的设计和豆瓣是不是一样，把自己账号删除了，现在感觉重新注册一周了，任然无法发帖并且有头像还说自己要上传头像，这是bug吗？
