### ISSUE TITLE
给用户的收藏做个搜索，大家觉得怎样？

### ISSUE THREAD

**Issue by chanshunli** [ruby-china/homeland#409]
喜欢的帖子，我们会把它收藏起来，但页数多了，就不好找到自己收藏的帖子了。

如果可以的话，这个功能让我来做吧 :smile:

**Comment by zhagnx** [comment]
好点子。


2015-05-30 22:25 GMT+09:00 Steve Chan <notifications@github.com>:

**Comment by angelfan** [comment]
需要这个功能！！！

**Comment by Matrixbirds** [comment]
兹辞啊

**Comment by FlowerWrong** [comment]
+1

**Comment by diguage** [comment]
👍

**Comment by huacnlee** [comment]
打开收藏页面 Command + F

**Comment by Matrixbirds** [comment]
还是做成前端查询体验会好点 浏览器的不够酷炫
