### ISSUE TITLE
自动下载内容中三方网站的图片到 Ruby China 类似 GitHub 的做法，避免丢失

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#512]
同时也能避免非 SSL 的图片链接

**Comment by huobazi** [comment]
这个要赞 :+1: 

避免引入非自己域的东西，同时增强了安全性。

**Comment by huobazi** [comment]
GitHub 用的是反向代理，目的是解决非 SSL 资源引入问题

https://github.com/blog/743-sidejack-prevention-phase-3-ssl-proxied-assets
https://github.com/atmos/camo

这个可以是个思路，甚至直接拿来给 Ruby China 用上，然后再利用 UpYun 的 CDN 功能来抓反代输出的内容直接保存到云端， rails 这里几乎不用动代码了。

**Comment by songjiayang** [comment]
+1

**Comment by huobazi** [comment]
http://distinctplace.com/infrastructure/2013/09/18/use-nginx-to-proxy-files-from-remote-location-using-x-accel-redirect/

https://gist.github.com/bennylope/1297267

**Comment by huacnlee** [comment]
放入日程

1. 增加配置文件可以设置 proxy host
2. homeland-docker Nginx 默认带 proxy 的配置
