### ISSUE TITLE
 搜索内容分页显示问题

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/homeland#651]
问题描述：第一页内容为空，第二页开始有数据

![screen shot 2016-05-14 at 12 29 04 am](https://cloud.githubusercontent.com/assets/1459834/15254754/050f476a-196b-11e6-9501-e75ce2fe968b.png)

![screen shot 2016-05-14 at 12 29 13 am](https://cloud.githubusercontent.com/assets/1459834/15254756/05364b26-196b-11e6-9f73-ad8376a0f7f7.png)

cc @huacnlee

**Comment by yfractal** [comment]
ruby-china 调整了每页帖子的数量，这个问题没办法重现了。

<img width="655" alt="screen shot 2016-11-05 at 12 17 56 pm" src="https://cloud.githubusercontent.com/assets/3775525/20027542/f06935b6-a351-11e6-98d5-eb58beac91af.png">
