### ISSUE TITLE
首页精华帖展示部分没有做字长限制

### ISSUE THREAD

**Issue by Matrixbirds** [ruby-china/homeland#658]
![image](https://cloud.githubusercontent.com/assets/9990676/15355238/1e41246c-1d24-11e6-9f84-639ae3c34728.png)

**Comment by Matrixbirds** [comment]
解决方案
```bash
app/views/topics/_topic.html.erb
```
```ruby
  <%= link_to(truncate(topic.title, length: 40), topic_path(topic), title: topic.title) %>
```

**Comment by zlx** [comment]
这种方案在不同设备上显示会出现问题，最好是使用 CSS 来根据各平台确定宽度 https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.2/dist/css/bootstrap.css#L5679-L5683

**Comment by huacnlee** [comment]
是的，不应该靠裁剪来实现，应该用 CSS

**Comment by huacnlee** [comment]
🎉🎉🎉 解决老问题
