### ISSUE TITLE
组织成员数量计算错误

### ISSUE THREAD

**Issue by Martin91** [ruby-china/homeland#750]
组织列表页面中：
![image](https://cloud.githubusercontent.com/assets/2900644/18637350/ab567414-7ebe-11e6-964e-58180120f241.png)

分别查看两个团队的实际成员列表，发现数量有出入：
![image](https://cloud.githubusercontent.com/assets/2900644/18637397/cc0ca9da-7ebe-11e6-93ff-6715bcb45b6a.png)
![image](https://cloud.githubusercontent.com/assets/2900644/18637441/f2696a3c-7ebe-11e6-98e3-c38819392d24.png)

我回头争取尽早修复一下。

**Comment by cqcn1991** [comment]
路过一下...你也在南山？

**Comment by Martin91** [comment]
是啊，后海，话说，歪楼了吧？
cqcn1991 <notifications@github.com>于2016年9月22日 周四下午11:43写道：

**Comment by huacnlee** [comment]
未接受的没拍出

**Comment by Martin91** [comment]
好，那我弄一下
Jason Lee <notifications@github.com>于2016年9月22日 周四下午11:52写道：
