### ISSUE TITLE
多张图片情况下，预览效果和实际效果不一致

### ISSUE THREAD

**Issue by zlx** [ruby-china/homeland#759]
![image](https://cloud.githubusercontent.com/assets/1835854/18807921/af25adc8-8286-11e6-93f2-3df7c22d9feb.png)
![image](https://cloud.githubusercontent.com/assets/1835854/18807926/bd223a86-8286-11e6-8220-b83c8961e158.png)

预期如预览一样排版

**Comment by songjiayang** [comment]
需求描述没看太明白 ...

**Comment by zlx** [comment]
实际帖子里面变成了一行一张图片（点击放大看就会很明显），导致后面一大块空白。

这里我是特意把图片调整了大小，使它可以排在同一行。

需求可能不是很普遍，可以选择忽略
