### ISSUE TITLE
改进 iOS Push 的到达率

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#770]
70% 的时候都收不到...

**Comment by songjiayang** [comment]
iOS 上的 safari 浏览器吗？好奇 70% 是如何统计出来的

**Comment by huacnlee** [comment]
我收到的概率，估计 哈哈哈
songjiayang <notifications@github.com>于2016年10月10日 周一下午6:30写道：

**Comment by huacnlee** [comment]
客户端
Jason Lee <huacnlee@gmail.com>于2016年10月10日 周一下午7:31写道：

**Comment by huobazi** [comment]
我的都是打开 app 才看到通知上的红数字的

**Comment by huacnlee** [comment]
原因是 Bug 导致，没有触发 51469b6e94a2b7598e53afa23a63cbe225b3ac1c

**Comment by songjiayang** [comment]
cool, 昨晚开始，通知很到位

2016-10-31 18:21 GMT+08:00 Jason Lee <notifications@github.com>:
