### ISSUE TITLE
作为新手，没有办法回复帖子，很诡异，无提示直接跳转首页

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/homeland#784]
请求响应200，但是返回内容如下：

![screen shot 2016-10-21 at 1 51 42 pm](https://cloud.githubusercontent.com/assets/1459834/19588061/afad147e-9795-11e6-8e20-a6b617c6c8f4.png)

测试网站： http://try.gethomeland.com/topics/3

**Comment by huacnlee** [comment]
http://try.gethomeland.com/topics/2

可以的呀？

**Comment by songjiayang** [comment]
很奇怪，又可以了
