### ISSUE TITLE
搜索结果标题与链接地址对应错误

### ISSUE THREAD

**Issue by klaus01** [ruby-china/homeland#786]
如该搜索链接 https://ruby-china.org/search?q=%E4%BB%80%E4%B9%88%E6%97%B6%E5%80%99 ，下图中

![qq20161027-1](https://cloud.githubusercontent.com/assets/338228/19750110/0fcb0598-9c21-11e6-94ed-4d39267a2761.png)

点击帖子 `有个新手问题，一直很困惑，在类内定义一个实例变量 @x，在调用时候什么时候用 @x,什么时候省略直接用 x,` 打开的是 `[OT]你是从什么时候知道屏幕显示的原理是由像素点组成的？` 是下个帖子的链接。

初步查看，是第 n 个帖子的标题链接到了 n + 1 帖子的链接上，但最前面的几个帖子没有这个问题。

**Comment by huacnlee** [comment]
奇怪，就这个场景有问题

**Comment by narutoqqasd** [comment]
搜索rails 5的时候同样存在这个问题 https://ruby-china.org/search?q=rails+5  。。。

**Comment by lihuazhang** [comment]
这个是做了什么操作之后，没有更新es的索引，重新import下就好了。

**Comment by huacnlee** [comment]
已修复

**Comment by lihuazhang** [comment]
这个问题我们之前也遇到。 rubychina的代码是把更新es 扔给队列执行的吧，这个就会有问题。 我在testerhome 改成同步，只要更新就会去更新es的index后，就没遇到了。

有可能 SearchIndexer 这个做的不够及时。
