### ISSUE TITLE
控制台 -》节点=》排序的数字不起作用

### ISSUE THREAD

**Issue by lihuazhang** [ruby-china/homeland#808]
![image](https://cloud.githubusercontent.com/assets/872749/20517267/49953c6c-b0d5-11e6-937e-8949da68a618.png)

![image](https://cloud.githubusercontent.com/assets/872749/20517369/b81d4a08-b0d5-11e6-838e-c30e3a45d898.png)

如图，我设置了两个节点的大小。但是并不起作用

![image](https://cloud.githubusercontent.com/assets/872749/20517307/753a6874-b0d5-11e6-9943-7c10df374a0d.png)

![image](https://cloud.githubusercontent.com/assets/872749/20518619/c2c76d1c-b0da-11e6-9c05-9fc2650121a1.png)

section.nodes 返回的排序不对。

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/pull/809
