### ISSUE TITLE
登录提示『The change you wanted was rejected.』

### ISSUE THREAD

**Issue by Youngv** [ruby-china/homeland#814]
登录的时候提示如下图
<img width="755" alt="2016-11-30 2 47 01" src="https://cloud.githubusercontent.com/assets/1787625/20742607/08a0d166-b70c-11e6-8f07-b9b065704cce.png">

**Comment by huacnlee** [comment]
Ruby China 登陆的？还是哪里？

**Comment by chenhengjie123** [comment]
我的账号之前也出现过，后面用 github 登录一次就正常了。当时忘了截图。。。

**Comment by Youngv** [comment]
@huacnlee Ruby China 登陆，之前出现过一次，然后过了两天登录又正常了，刚才发现登录又正常了

**Comment by huacnlee** [comment]
已修复，请试试看呢
