### ISSUE TITLE
编辑器的bug?

### ISSUE THREAD

**Issue by Matrixbirds** [ruby-china/homeland#815]
<img width="1208" alt="2016-12-02 12 10 04" src="https://cloud.githubusercontent.com/assets/9990676/20822782/8a52c3a4-b888-11e6-855d-dc0b25c1086a.png">
<img width="892" alt="2016-12-02 12 10 17" src="https://cloud.githubusercontent.com/assets/9990676/20822783/8bdd86e6-b888-11e6-9e97-802893c38ff5.png">

**Comment by huacnlee** [comment]
说一下操作的过程，我看看能不能重现出来
