### ISSUE TITLE
节点描述处的html标签被未被解析，导致markdown失效

### ISSUE THREAD

**Issue by W3INFO** [ruby-china/homeland#826]
http://try.gethomeland.com/topics/node36

![image](https://cloud.githubusercontent.com/assets/17700488/21253666/52cd106a-c39b-11e6-8c32-7644f057177b.png)

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/commit/8a2360bae110f38f42bdfa5f254e3660867f648b

**Comment by W3INFO** [comment]
docker  没更新~~  无语
