### ISSUE TITLE
lib/homeland/markdown.rb报错：can't find string "EXAMPLE" anywhere before EOF 

### ISSUE THREAD

**Issue by shuke0327** [ruby-china/homeland#844]
在本地跑homeland的代码，遇到如下的错误(ruby: 2.2.5, Raisl: 5.0.0.1)
can't find string "EXAMPLE" anywhere before EOF (SyntaxError)

报错出在：/homeland/lib/homeland/markdown.rb　这个文件中。

原内容：
@example ||= <<~EXAMPLE
.....
EXAMPLE

修改为：
@example ||= <<-EXAMPLE
.....
EXAMPLE

之后，不再报错。
对<<~的用法比较陌生，请问是需要依赖Ruby的哪个版本？还是我忽略了这部分的内容呢？

谢谢。

**Comment by huacnlee** [comment]
Ruby 2.3 以上
