### ISSUE TITLE
关于支持github登录

### ISSUE THREAD

**Issue by wangxinghe** [ruby-china/homeland#852]
我自己搭建一个网站http://talkcode.cc/ 想支持github登录功能。
网上查了资料，在https://github.com/settings/developers注册了application，得到client id和client secret，
然后就是看了这个文档http://gethomeland.com/docs/sso/as-client/ ，但是也没有太看懂，SingleSignOn的代码不知道具体写到哪个位置。。不知道能不能详细解答一下呢？
我用的homeland的开源框架，已经搭建好了，服务器上有homeland-docker目录。
十分感谢！

**Comment by huacnlee** [comment]
SSO 是单点登录，不是 GitHub 那个（那个是 OAuth 2 登录，暂时没写文档），GitHub 那个只需要配置好 client_id 和 secret 就可以了。

**Comment by wangxinghe** [comment]
@huacnlee 谢谢
