### ISSUE TITLE
:user/favorites 和 topics/favorites 两个动作显示的话题顺序不一致

### ISSUE THREAD

**Issue by pinewong** [ruby-china/homeland#861]
从用户页查看收藏话题(:user/favorites)显示是按收藏时间逆序的，感觉比较正常；
但从全局直接进入查看收藏话题(topics/favorites)显示却是根据发帖时间的。

源码 topics_controller 和 users/user_actions 里的 favorites 方法很像，但是被注释了一行，因此出现这样的情况不知道是管理员有意为之还是没注意到这个地方？

**Comment by huacnlee** [comment]
新结构将会发布会 https://github.com/ruby-china/homeland/pull/857
