### ISSUE TITLE
代码更新到最新版本，启动服务

### ISSUE THREAD

**Issue by gaolei** [ruby-china/homeland#879]
构建开发环境出错

$ git clone https://github.com/ruby-china/homeland.git
$ cd homeland
$ ./bin/setup
Checking Package Dependencies...

出现异常

NoMethodError: undefined method `match?' for "section_node_updated_at=":String
/vagrant/app/models/cache_version.rb:14:in `rescue in method_missing'
/vagrant/app/models/cache_version.rb:11:in `method_missing'
/vagrant/app/models/section.rb:15:in `update_cache_version'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `block in call'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `each'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `call'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:125:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/validations.rb:44:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:319:in `block in save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:318:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/suppressor.rb:41:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:34:in `create'
/vagrant/db/seeds.rb:2:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:549:in `load_seed'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `section_node_updated_at=' for CacheVersion:Class
/vagrant/app/models/cache_version.rb:12:in `method_missing'
/vagrant/app/models/section.rb:15:in `update_cache_version'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `block in call'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `each'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `call'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:125:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/validations.rb:44:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:319:in `block in save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:318:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/suppressor.rb:41:in `save'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:34:in `create'
/vagrant/db/seeds.rb:2:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:549:in `load_seed'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/var/lib/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

通过Vagrant 构建应用程序后，启动服务后出错。rails s -b 0.0.0.0

ActionView::Template::Error (undefined method `match?' for #<String:0x00000008414990>):
    21:   </div>
    22: </div>
    23: 
    24: <% if !mobile? %>
    25:   <%= render "/shared/index_sections" %>
    26:   <%= render "/shared/hot_locations" %>
    27: <% end %>
  
app/helpers/application_helper.rb:67:in `mobile?'
app/views/home/index.html.erb:24:in `_app_views_home_index_html_erb__1817708730821551442_68944740'
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.8ms)
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.5ms)
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (24.0ms)

环境：ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]
gem :

action-store (0.3.0, 0.2.1)
actioncable (5.0.1, 5.0.0)
actionmailer (5.0.1, 5.0.0)
actionpack (5.0.1, 5.0.0)
actionview (5.0.1, 5.0.0)
activejob (5.0.1, 5.0.0)
activemodel (5.0.1, 5.0.0)
activerecord (5.0.1, 5.0.0)
activesupport (5.0.1, 5.0.0)
addressable (2.5.0)
aliyun-oss-sdk (0.1.8)
arel (7.1.4)
ast (2.3.0)
auto-space (0.0.4)
bcrypt (3.1.11)
benchmark-ips (2.7.2)
better_errors (2.1.1)
bigdecimal (1.2.8)
binding_of_caller (0.7.2)
builder (3.2.3)
bulk_insert (1.4.0)
bundler (1.14.5)
bundler-audit (0.5.0)
cancancan (1.16.0)
capybara (2.12.0)
carrierwave (1.0.0)
carrierwave-aliyun (0.8.1)
carrierwave-upyun (0.2.2)
codecov (0.1.9)
coderay (1.1.1)
coffee-rails (4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5, 1.0.4)
connection_pool (2.2.1)
crass (1.0.2)
dalli (2.7.6)
database_cleaner (1.5.3)
debug_inspector (0.0.2)
derailed (0.1.0)
derailed_benchmarks (1.3.2)
devise (4.2.0)
devise-encryptable (0.2.0)
diff-lcs (1.3)
docile (1.1.5)
doorkeeper (4.2.5)
doorkeeper-i18n (4.0.0)
dropzonejs-rails (0.7.3)
elasticsearch (5.0.3)
elasticsearch-api (5.0.3)
elasticsearch-model (0.1.9)
elasticsearch-rails (0.1.9)
elasticsearch-transport (5.0.3)
erubis (2.7.0)
exception-track (0.2.0)
exception_notification (4.2.1)
execjs (2.7.0)
factory_girl (4.8.0)
factory_girl_rails (4.8.0)
faraday (0.10.1)
ffi (1.9.17)
font-awesome-rails (4.7.0.1)
get_process_mem (0.2.1)
globalid (0.3.7)
gyoku (1.3.1)
hashie (3.5.3)
heapy (0.1.2)
hiredis (0.6.1)
homeland-press (0.2.1, 0.1.0)
html-pipeline (2.5.0)
html-pipeline-rouge_filter (1.0.4)
http_accept_language (2.1.0)
httparty (0.14.0)
i18n (0.8.1, 0.8.0)
io-console (0.4.5)
jbuilder (2.6.1)
jquery-atwho-rails (1.3.2)
jquery-rails (4.2.2)
json (2.0.3, 1.8.3)
jwt (1.5.6)
kaminari (1.0.1)
kaminari-actionview (1.0.1)
kaminari-activerecord (1.0.1)
kaminari-core (1.0.1)
kgio (2.11.0)
launchy (2.4.3)
letter_avatar (0.3.2)
letter_opener (1.4.1)
listen (3.1.5)
loofah (2.0.3)
mail (2.6.4)
memory_profiler (0.9.7)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_magick (4.6.1)
mini_portile2 (2.1.0)
minitest (5.10.1)
multi_json (1.12.1)
multi_xml (0.6.0)
multipart-post (2.0.0)
nio4r (1.2.1)
nokogiri (1.7.0.1)
nokogumbo (1.4.10)
notifications (0.4.0)
oauth2 (1.3.0)
omniauth (1.4.2)
omniauth-github (1.2.2)
omniauth-oauth2 (1.4.0)
orm_adapter (0.5.0)
parser (2.4.0.0)
pg (0.19.0)
pghero (1.6.3)
postmark (1.10.0)
postmark-rails (0.15.0)
powerpack (0.1.1)
psych (2.1.0)
public_suffix (2.0.5)
puma (3.7.0)
rack (2.0.1)
rack-attack (5.0.1)
rack-cors (0.4.1)
rack-protection (2.0.0.beta2)
rack-test (0.6.3)
rack-utf8_sanitizer (1.3.2)
rails (5.0.1, 5.0.0)
rails-dom-testing (2.0.2)
rails-html-sanitizer (1.0.3)
rails-i18n (5.0.3)
rails-settings-cached (0.6.5)
rails_autolink (1.1.6)
railties (5.0.1, 5.0.0)
rainbow (2.1.0)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (4.2.1)
redcarpet (3.4.0)
redis (3.3.3)
redis-namespace (1.5.2)
redis-objects (1.2.1)
redis-session-store (0.9.1)
responders (2.3.0)
rouge (1.11.1)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-rails (3.5.2)
rspec-support (3.5.0)
rubocop (0.47.1)
ruby-progressbar (1.8.1)
ruby-push-notifications (1.0.1)
ruby_dep (1.5.0)
rucaptcha (2.0.3)
sanitize (4.4.0)
sass (3.4.23)
sass-rails (5.0.6)
second_level_cache (2.3.0.beta)
sidekiq (4.2.9)
simple_form (3.4.0)
simplecov (0.13.0)
simplecov-html (0.10.0)
social-share-button (0.8.8)
spring (2.0.1)
spring-commands-rspec (1.0.4)
sprockets (3.7.1)
sprockets-rails (3.2.0)
status-page (0.1.4)
thor (0.19.4)
thread_safe (0.3.6, 0.3.5)
tilt (2.0.6)
turbolinks (5.0.1)
turbolinks-source (5.0.0)
twemoji (3.1.1)
tzinfo (1.2.2)
uglifier (3.0.4)
unicode-display_width (1.1.3)
url (0.3.2)
warden (1.2.7)
websocket-driver (0.6.5)
websocket-extensions (0.1.2)
xpath (2.0.0)
yard (0.9.8)

**Comment by huacnlee** [comment]
用 Ruby 2.4

现在里面已经有 Ruby 2.4 的语法了。

**Comment by gaolei** [comment]
更新到ruby2.4后，./bin/setup 正常通过。

重新建立索引，无法成功。
rails elasticsearch:import:model CLASS=Page FORCE=y

获得以下错误信息：

/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
rails aborted!
NameError: uninitialized constant Page
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `eval'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `eval'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/vagrant/bin/rails:9:in `require'
/vagrant/bin/rails:9:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/vagrant/bin/spring:13:in `require'
/vagrant/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => elasticsearch:import:model
(See full trace by running task with --trace)


elasticsearch 服务已经启动
sudo service elasticsearch start

当前环境
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

gem:

*** LOCAL GEMS ***

action-store (0.3.0)
actioncable (5.0.1)
actionmailer (5.0.1)
actionpack (5.0.1)
actionview (5.0.1)
activejob (5.0.1)
activemodel (5.0.1)
activerecord (5.0.1)
activesupport (5.0.1)
addressable (2.5.0)
aliyun-oss-sdk (0.1.8)
arel (7.1.4)
ast (2.3.0)
auto-space (0.0.4)
bcrypt (3.1.11)
benchmark-ips (2.7.2)
better_errors (2.1.1)
bigdecimal (default: 1.3.0)
binding_of_caller (0.7.2)
builder (3.2.3)
bulk_insert (1.4.0)
bundler (1.14.5)
bundler-audit (0.5.0)
bundler-unload (1.0.2)
cancancan (1.16.0)
capybara (2.12.0)
carrierwave (1.0.0)
carrierwave-aliyun (0.8.1)
carrierwave-upyun (0.2.2)
codecov (0.1.9)
coderay (1.1.1)
coffee-rails (4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
connection_pool (2.2.1)
crass (1.0.2)
dalli (2.7.6)
database_cleaner (1.5.3)
debug_inspector (0.0.2)
derailed (0.1.0)
derailed_benchmarks (1.3.2)
devise (4.2.0)
devise-encryptable (0.2.0)
did_you_mean (1.1.0)
diff-lcs (1.3)
docile (1.1.5)
doorkeeper (4.2.5)
doorkeeper-i18n (4.0.0)
dropzonejs-rails (0.7.3)
elasticsearch (5.0.3)
elasticsearch-api (5.0.3)
elasticsearch-model (0.1.9)
elasticsearch-rails (0.1.9)
elasticsearch-transport (5.0.3)
erubis (2.7.0)
exception-track (0.2.0)
exception_notification (4.2.1)
execjs (2.7.0)
executable-hooks (1.3.2)
factory_girl (4.8.0)
factory_girl_rails (4.8.0)
faraday (0.10.1)
ffi (1.9.17)
font-awesome-rails (4.7.0.1)
gem-wrappers (1.2.7)
get_process_mem (0.2.1)
globalid (0.3.7)
gyoku (1.3.1)
hashie (3.5.3)
heapy (0.1.2)
hiredis (0.6.1)
homeland-press (0.2.1)
html-pipeline (2.5.0)
html-pipeline-rouge_filter (1.0.4)
http_accept_language (2.1.0)
httparty (0.14.0)
i18n (0.8.1)
io-console (default: 0.4.6)
jbuilder (2.6.1)
jquery-atwho-rails (1.3.2)
jquery-rails (4.2.2)
json (2.0.3, default: 2.0.2)
jwt (1.5.6)
kaminari (1.0.1)
kaminari-actionview (1.0.1)
kaminari-activerecord (1.0.1)
kaminari-core (1.0.1)
kgio (2.11.0)
launchy (2.4.3)
letter_avatar (0.3.2)
letter_opener (1.4.1)
listen (3.1.5)
loofah (2.0.3)
mail (2.6.4)
memory_profiler (0.9.7)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_magick (4.6.1)
mini_portile2 (2.1.0)
minitest (5.10.1)
multi_json (1.12.1)
multi_xml (0.6.0)
multipart-post (2.0.0)
net-telnet (0.1.1)
nio4r (1.2.1)
nokogiri (1.7.0.1)
nokogumbo (1.4.10)
notifications (0.4.0)
oauth2 (1.3.0)
omniauth (1.4.2)
omniauth-github (1.2.2)
omniauth-oauth2 (1.4.0)
openssl (default: 2.0.2)
orm_adapter (0.5.0)
parser (2.4.0.0)
pg (0.19.0)
pghero (1.6.3)
postmark (1.10.0)
postmark-rails (0.15.0)
power_assert (0.4.1)
powerpack (0.1.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
puma (3.7.0)
rack (2.0.1)
rack-attack (5.0.1)
rack-cors (0.4.1)
rack-protection (2.0.0.beta2)
rack-test (0.6.3)
rack-utf8_sanitizer (1.3.2)
rails (5.0.1)
rails-dom-testing (2.0.2)
rails-html-sanitizer (1.0.3)
rails-i18n (5.0.3)
rails-settings-cached (0.6.5)
rails_autolink (1.1.6)
railties (5.0.1)
rainbow (2.1.0)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (default: 5.0.0)
redcarpet (3.4.0)
redis (3.3.3)
redis-namespace (1.5.2)
redis-objects (1.2.1)
redis-session-store (0.9.1)
responders (2.3.0)
rouge (1.11.1)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-rails (3.5.2)
rspec-support (3.5.0)
rubocop (0.47.1)
ruby-progressbar (1.8.1)
ruby-push-notifications (1.0.1)
ruby_dep (1.5.0)
rubygems-bundler (1.4.4)
rucaptcha (2.0.3)
rvm (1.11.3.9)
sanitize (4.4.0)
sass (3.4.23)
sass-rails (5.0.6)
second_level_cache (2.3.0.beta)
sidekiq (4.2.9)
simple_form (3.4.0)
simplecov (0.13.0)
simplecov-html (0.10.0)
social-share-button (0.8.8)
spring (2.0.1)
spring-commands-rspec (1.0.4)
sprockets (3.7.1)
sprockets-rails (3.2.0)
status-page (0.1.4)
test-unit (3.2.3)
thor (0.19.4)
thread_safe (0.3.6)
tilt (2.0.6)
turbolinks (5.0.1)
turbolinks-source (5.0.0)
twemoji (3.1.1)
tzinfo (1.2.2)
uglifier (3.0.4)
unicode-display_width (1.1.3)
url (0.3.2)
warden (1.2.7)
websocket-driver (0.6.5)
websocket-extensions (0.1.2)
xmlrpc (0.2.1)
xpath (2.0.0)
yard (0.9.8)

**Comment by huacnlee** [comment]
你不需要用到哪个命令，那个命令用处很少，不要在意开发文档的错误

**Comment by gaolei** [comment]
希望给homeland做一些开发的贡献，所以搭建开发环境。

刚才源码服务启动的时候，测试流程中，创建帖子时出现异常，看起来和索引有关。看说明内容觉得可能是没有建立索引，所以尝试了文档的索引重建。

跑了一下 bundle exec rake 。然后再次创建帖子，异常没有再出现。
