### ISSUE TITLE
UI 重构或细节优化

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#885]

**Comment by songjiayang** [comment]
![img_7333](https://cloud.githubusercontent.com/assets/1459834/23613162/37cd2522-02b9-11e7-9d02-97458a190d50.PNG)

貌似帖子目录样式在手机上有点问题，遮挡了内容，而且不是 fixed 的

**Comment by lihuazhang** [comment]
有些细节可以借鉴http://discuss.flarum.org.cn/。或者 discourse

**Comment by humwicked** [comment]
是啊，移动端进入帖子内容页面，点击“目录”按钮，弹出的目录页面就无法返回帖子内容了！还有移动端wiki页面也是破位了。UI这方面 flarum 值得借鉴！
