### ISSUE TITLE
账号可以随便锁定

### ISSUE THREAD

**Issue by yougar0** [ruby-china/homeland#895]
require 'net/http'

uri = URI('https://ruby-china.org/account/sign_in')

10.times do
        res = Net::HTTP.post_form(uri, 'utf8' => "&#x2713;",'user[login]' => "xxxxxx", 'user[password]' => "xxxxxxx", 'user[remember_me]' => "0", 'commit' => "登录")
end

puts 'Happy!'

这个执行一次,然后你的账号莫名就被锁了？ 这是个BUG吗？ 还是就是这样设计的 为了用户安全？？

**Comment by huacnlee** [comment]
实现不完整，应该多次尝试以后出验证码的

**Comment by yougar0** [comment]
恩 我也这样觉得 反暴力破解这个方法很管用！ 期待验证码ing！

**Comment by songjiayang** [comment]
@yougar0  如果是 APP,没必要使用账号密码登录，你可以注册应用使用 ak/sk

**Comment by yougar0** [comment]
@songjiayang 可以 App很强
