### ISSUE TITLE
建议:使用名字而不是login

### ISSUE THREAD

**Issue by lihuazhang** [ruby-china/homeland#897]
感觉使用名字会比使用login更亲切一点，像qq，微信一样，在别人眼里，一般都只看到昵称。

login相对生硬而且把这个暴露出来似乎也不是安全的事情。

我试着改了下，但不是很理想，比如后台用login比较合理。

**Comment by NeverMin** [comment]
我猜你是指 @lihuazhang 的时候使用昵称对吗? 例如 @恒星
如果是的话, 那么正常的中文字还好...一堆奇奇怪怪的名字, 或是火星文, 应该没有人会 @ 吧.
如果直接卡死不让输入, 好像又有点不近人情(不人性).

**Comment by huacnlee** [comment]
看不懂，说那里？

**Comment by lihuazhang** [comment]
@NeverMin 你这一说也是很有道理的。 @huacnlee 是说论坛里用户名的露出。
