### ISSUE TITLE
成员列表支持取消邀请和移除成员

### ISSUE THREAD

**Issue by 42thcoder** [ruby-china/homeland#920]
URL: https://ruby-china.org/skio/people

两个场景:

- 管理员手贱邀请了非公司成员, 无法取消邀请; 该同学的话题还会出现在成员的话题列表
- 成员离职

**Comment by huacnlee** [comment]
修改成员界面有的

**Comment by 42thcoder** [comment]
看代码好像确实有的

```ruby
    <% if can? :update, @team && team_user.user_id != current_user&.id %>
      <%= link_to icon_tag('pencil'), edit_user_team_user_path(@team, team_user), class: 'btn btn-default' %>
    <% end %>
```

但是界面上没有, 是我没权限么? 我应该是组织的创建者的.

![image](https://cloud.githubusercontent.com/assets/1809973/25474708/b8bc176c-2b66-11e7-860d-bf83d4f1844e.png)

**Comment by huacnlee** [comment]
想帮你移除了

**Comment by 42thcoder** [comment]
LOL 

那先帮忙把 Cam 移除吧

**Comment by NeverMin** [comment]
点击该成员后面的修改, 然后就会看到移除成员.

-Never

**Comment by 42thcoder** [comment]
@NeverMin 

> 点击该成员后面的修改, 然后就会看到移除成员.


盯着截图看了半天, 没有找到 "修改"....

**Comment by NeverMin** [comment]
@42thcoder 抱歉, 我是用管理员进来才看到, 组管理员好像没权限.

**Comment by huacnlee** [comment]
有 Bug 是需要等修复
