### ISSUE TITLE
Homeland 有说明 Ruby 支持版本吗？

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/homeland#925]
ruby 2.3.1 运行程序报错：

![screen shot 2017-05-16 at 2 20 05 pm](https://cloud.githubusercontent.com/assets/1459834/26092299/cf48b34c-3a42-11e7-962e-2f02f67b1a7b.png)

检查了下， ruby 2.4  `String`  才引入 `match?` 的.

**Comment by NeverMin** [comment]
对的, 就是 2.4
见 #879

**Comment by songjiayang** [comment]
既然如此，是不是 gemfile 里面需要指定 ruby_version

**Comment by neilxp** [comment]
强烈要求写上ruby版本号，找到这里才知道！

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/blob/master/CONTRIBUTE.md
