### ISSUE TITLE
注册时没有进行邮箱验证导致被冒用

### ISSUE THREAD

**Issue by KaiyangNi** [ruby-china/homeland#942]
注册时并没有相应的验证码验证邮箱是否是注册人所有，导致邮箱被冒用身份注册

**Comment by lgn21st** [comment]
@KaiyangNi 那么你可以通过找回密码功能，拿到冒用你邮箱的人的账号吧？

**Comment by KaiyangNi** [comment]
@lgn21st 关键是，如果之前那个人在这个邮箱的账号留下各种不良的记录，这对这个邮箱真实用户有印象啊，比如一些发广告的随便用你的邮箱注册之后发广告。

**Comment by lgn21st** [comment]
@KaiyangNi 明白你的意思，问题是 RubyChina 是非赢利组织，所以没有办法在邮箱服务和邮件到达率上投入太多的资源，以及开发时间和运营时间，导致的结果就是无法强制要求邮箱验证。

我想想有没有什么办法，其实从我的角度，只保留 github oauth 登陆，对于技术社区来说就够了，但是大量的小白用户和 HR 用户连 github 账号都没有也头疼。

**Comment by huacnlee** [comment]
找回密码
