### ISSUE TITLE
使用 simplemde 作为 markdown 编辑器

### ISSUE THREAD

**Issue by lihuazhang** [ruby-china/homeland#950]
https://simplemde.com/

看隔壁 https://laravel-china.org/articles/create 的 form 很不错。

![image](https://user-images.githubusercontent.com/872749/29423804-b47a637e-83af-11e7-9fd1-a07a56f0e5ac.png)

**Comment by huobazi** [comment]
像文件存储那样对 body 的格式 做成 provider 不仅限于 markdown 比较好

**Comment by humwicked** [comment]
貌似这个编辑器bug挺多的，使用体验并不是太好！我觉得还不如自制增添一些常用的快捷键上去！比如homeland现有的表情、代码、图片上传快捷键！目前看着再增加一些加粗、H tag、引用、有序、无线快捷键就差不多了吧！

**Comment by YUFENGWANG** [comment]
我需要上传文件的功能，能否加一个~

**Comment by NeverMin** [comment]
我是用百度网盘的。

-Never
