### ISSUE TITLE
根据方法安装后，请求首页是nginx的页面，怎么才能跳转过去？

### ISSUE THREAD

**Issue by chenchiwei** [ruby-china/homeland#958]
如题

**Comment by NeverMin** [comment]
设好 ServerName 和 root path

**Comment by chenchiwei** [comment]
哪里设？难道安装的方式不对？我是根据https://gethomeland.com/install/ 上面的方法安装的

**Comment by NeverMin** [comment]
抱歉，我没有用过 docker 的方式，把问题留给其他人。

-Never

2017-10-12 14:53 GMT+08:00 ChervyChen <notifications@github.com>:

**Comment by huacnlee** [comment]
https://gethomeland.com/docs/configuration/config-file/

读过没？

**Comment by chenchiwei** [comment]
嗯，看了，估计是我直接使用默认配置导致的，我在ruby-china上也找到类似的问题，已经解决了，谢谢
