### ISSUE TITLE
怎么设置开发环境？

### ISSUE THREAD

**Issue by uxgnod** [ruby-china/homeland#969]
想请问一下，现在如果现在本地开发 homeland 的话，是怎么设置开发环境呢？
是换成了 Docker 吗？
还是想之前一样，继续用 vagrant，因为不知道 Vagrantfile 是不是还在维护。而且之前 README 里面是给出了具体的步骤的，现在变成了指向 homeland 官网的链接，而官网给出的是 Docker 的方法。

**Comment by lokyoung** [comment]
https://github.com/ruby-china/homeland/blob/master/CONTRIBUTE.md
