### ISSUE TITLE
想问下homeland有没有什么好的备份方案？

### ISSUE THREAD

**Issue by ghost** [ruby-china/homeland#976]
小白刚开始折腾这个，用docker安装的完全不知道怎么备份怎么恢复，对于经常迁移服务器的我，感到很无力

**Comment by gonjay** [comment]
直接把所有的容器打包，用scp转移到其他服务器就可以？

**Comment by huacnlee** [comment]
https://github.com/huacnlee/gobackup

试试 GoBackup，你需要将 PostgreSQL 暴露给 Host 主机，以便于 GoBackup 可以链接，实现备份
