### ISSUE TITLE
docker启动后没有产生production.log

### ISSUE THREAD

**Issue by gonjay** [ruby-china/homeland#985]
网站链接: https://www.block-china.org
`homeland-docker/log` 下只有：
```
homeland-access.log  homeland-error.log  nginx-access.log  nginx-error.log  sidekiq.log
```
 这5个日志，没有看见production.log

尝试docker exec进去web的容器，在log目录下也没有看见production.log日志，不知道是哪里配置不对吗?

**Comment by huacnlee** [comment]
production.log 和 docker 融入在一起了

**Comment by gonjay** [comment]
还是没明白，我该去哪里查看production.log日志？

**Comment by huacnlee** [comment]
```
sudo docker logs [OPTIONS] CONTAINER
```

https://docs.docker.com/engine/reference/commandline/logs/
